import '@radix-ui/themes/styles.css';
import './theme-config.css';
import './globals.css';
import { Container, Theme, ThemePanel } from '@radix-ui/themes';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Navbar from './Navbar';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme accentColor="violet">
          <Navbar />
          <main className="p-5">
            <Container>{children}</Container>
            {/* {children} */}
          </main>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
